#keycloak:
#    realm: Oauth2
#    auth-server-url: https://sdevtest.genians.kr:30004/realms/Oauth2
#    resource: oauth2-client-app
#    bearer-only: true
#    ssl-required: external
#    principal-attribute: subject
#    use-resource-role-mappings: true

server:
    port: 8081
spring:
    security:
        oauth2:
            client:

                registration:
                    keycloak:
                        authorization-grant-type: authorization_code
                        client-id: oauth2-client-app
                        client-name: oauth2-client-app
                        client-secret: zakIo7yUuNuihdDBRibSDY3hdYtkN9x2
                        redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
                        scope: profile,email

                    google:
                        client-id: 1014956426473-1al44kadodjf6ai62qiupgtbaug8k4or.apps.googleusercontent.com
                        client-secret: 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
                        scope: openid,profile,email

                    naver:
                        client-id: fiz4MD1PwDOiwjfSPoqk
                        client-secret: DAT6Z0jvgg
                        authorization-grant-type: authorization_code
                        client-name: naver-client-app
                        redirect-uri: http://localhost:8081/login/oauth2/code/naver
                        scope: profile,email
                #                        scope: openid,profile,email

                provider:
                    keycloak:
                        authorization-uri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/auth
                        issuer-uri: https://sdevtest.genians.kr:30004/realms/Oauth2
                        jwk-set-uri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/certs
                        token-uri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/token
                        user-info-uri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/userinfo
                        user-name-attribute: preferred_username
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

    mvc:
        static-path-pattern: /static/**
